import { Roboto } from "next/font/google";
import Header from "./components/Header";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Next_13",
  description: "Generated by create next app",
  keywords:
    "html, css, javascript, web design,web development,react js,next js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
